language: cpp

sudo: required

services:
  - docker

compiler:
  - clang
  - gcc

env:
  global:
    - BOOST_TEST_AUTO_START_DBG=yes
    - BOOST_TEST_LOG_LEVEL=all
    - BOOST_TEST_SHOW_PROGRESS=yes
    - BOOST_TEST_DETECT_MEMORY_LEAK=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libsqlite3-dev

install:
  - git clone https://github.com/cybergarage/foreman-cc.git foreman-cc

script:
  - cd foreman-cc && ./bootstrap && ./configure --enable-tests && make && make check

notifications:
  email: false

after_failure:
  - cat tests/unix/test-suite.log
