#!/bin/bash

./beringei_setup
pushd include/foreman && ./Const.h.build && popd

pushd include && ./Makefile.am.build > Makefile.am && popd
pushd lib/unix && ./Makefile.am.build > Makefile.am && popd
pushd test/unix && ./Makefile.am.build > Makefile.am && popd
pushd bin/foremanbench/unix && ./Makefile.am.build > Makefile.am && popd
pushd bin/foremanusage/unix && ./Makefile.am.build > Makefile.am && popd

./format

if [ ! -d config ]; then
    mkdir config
fi
if [ ! -d autom4te.cache ]; then
	rm -rf autom4te.cache/*
fi
#libtoolize --automake --force --copy
aclocal
autoheader
automake --foreign --add-missing --copy
autoconf
