#!/bin/sh

pushd include && ./Makefile.am.build > Makefile.am && popd
pushd lib/unix && ./Makefile.am.build > Makefile.am && popd
pushd bin/foremanbench/unix && ./Makefile.am.build > Makefile.am && popd
pushd tests/unix && ./Makefile.am.build > Makefile.am && popd

if [ ! -d config ]; then
    mkdir config
fi
if [ ! -d autom4te.cache ]; then
	rm -rf autom4te.cache/*
fi
#libtoolize --automake --force --copy
aclocal
autoheader
automake --foreign --add-missing --copy
autoconf