#!/bin/bash
if [ `which python-config` ]; then
    export CFLAGS="$CFLAGS `python-config --includes`"
    export LDFLAGS="$LDFLAGS `python-config --libs`"
fi
export CXXFLAGS="$CFLAGS $CXXFLAGS -Wall -O2"
./configure --enable-alglib "$@"
