#!/bin/bash
export CFLAGS="-I/usr/local/include `python-config --includes`"
export CXXFLAGS="-std=c++11 $CFLAGS"
export LDFLAGS="-L/usr/local/lib  `python-config --libs`"
./configure --enable-alglib MKDIR_P='mkdir -p' $@
