#!/bin/bash
export CFLAGS="-I/usr/local/include `pkg-config --cflags lua` `python-config --includes`"
export CXXFLAGS="-std=c++14 $CFLAGS"
export LDFLAGS="-L/usr/local/lib  `pkg-config --libs lua` `python-config --libs`"
./configure --enable-script-lua --enable-script-python --enable-alglib MKDIR_P='mkdir -p' $@
