#!/bin/bash
export CFLAGS="$CFLAGS -I/usr/local/include"
export LDFLAGS="$LDFLAGS -L/usr/local/lib"

# Python
if [ `which python-config` ]; then
    export CFLAGS="$CFLAGS `python-config --includes`"
    export LDFLAGS="$LDFLAGS `python-config --libs`"
else
    if [ `which python3-config` ]; then
        export CFLAGS="$CFLAGS `python3-config --includes`"
        export LDFLAGS="$LDFLAGS `python3-config --libs`"
    fi
fi

# LUA
#export CFLAGS="$CFLAGS `pkg-config --cflags lua`"
#export LDFLAGS="$LDFLAGS `pkg-config --libs lua`"

export CXXFLAGS="$CFLAGS $CXXFLAGS -O0 -std=c++14"

#./configure --enable-beringei --enable-script-lua --enable-script-python --enable-alglib MKDIR_P='mkdir -p' $@
./configure --enable-alglib --enable-script-python MKDIR_P='mkdir -p' $@
