#!/bin/bash
export CFLAGS="`python-config --includes`"
export CXXFLAGS="$CFLAGS $CXXFLAGS -Wall -O2 `python-config --includes`"
export LDFLAGS="$LDFLAGS `python-config --libs`"
./configure --enable-alglib "$@"
