#!/bin/bash
if [ `which python3-config` ]; then
    export CFLAGS="$CFLAGS `python3-config --includes`"
    export LDFLAGS="$LDFLAGS `python3-config --ldflags`"
else
    if [ `which python-config` ]; then
        export CFLAGS="$CFLAGS `python-config --includes`"
        export LDFLAGS="$LDFLAGS `python-config --ldflags --embed`"
    fi
fi
export CXXFLAGS="$CFLAGS $CXXFLAGS -Wall -O0 -g3"
./configure --enable-script-python --enable-alglib --enable-test "$@"
