#!/bin/bash
sudo yum -y --enablerepo=extras install epel-release
sudo yum install -y wget
sudo yum install -y gcc gcc-c++ libgcc boost-devel automake cmake
sudo yum install -y sqlite-devel curl-devel libuuid-devel alglib-devel python-devel

# For Facebook-folly
sudo yum install -y \
    double-conversion-devel \
    glog-devel \
    gflags-devel \
    libevent-devel \
    openssl-devel
