#!/bin/bash

sudo apt-get install -y g++ automake libboost-all-dev make pkg-config
sudo apt-get install -y libsqlite3-dev libcurl3-dev uuid-dev libalglib-dev libossp-uuid-dev libpython3-all-dev
sudo apt-get install -y valgrind

# For facebook-folly
sudo apt-get -y install \
    cmake \
    antlr4 \
    libevent-dev \
    libdouble-conversion-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libiberty-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    libssl-dev

sudo apt autoremove -y

# For Python3 with valgrind
export PYTHONMALLOC=malloc_debug
