name: make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt update
        sudo apt-get install -y g++ automake libboost-all-dev make pkg-config
        sudo apt-get install -y libsqlite3-dev libcurl3-dev libalglib-dev uuid-dev libpython3-all-dev
        sudo apt-get install -y valgrind
    - name: configure
      run: ./configure_ubuntu
    - name: make
      run: make -j 20
    - name: make check
      run: make check -j 20 || more test/unix/test-suite.log
